server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: Users/andrade.sampaio/Documents/GitHub/spring-cloud/microservice-repo

